version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      MONGO_URI: mongodb://${MONGODB_USR}:${MONGODB_PWD}@mongodb:27017/civ-drafter
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network: